name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Build
        run: chmod +x ci/build-app.sh && ci/build-app.sh
      - name: Unit-test
        run: chmod +x ci/unit-test-app.sh && ci/unit-test-app.sh

